version: "3.9"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  backup:
    image: 0xff/postgres-backup
    environment:
      PGPASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./pg-backups:/pg-backups
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: -source=file://migrations -database $DATABASE_URL up
    restart: on-failure
    links:
      - database
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    depends_on:
      - database
      - migrate
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data:
